BATTLE_HISTORY = 'https://kohcamp.qq.com/game/morebattlelist'
BATTLE_DETAIL = 'https://kohcamp.qq.com/game/battledetail'
SEASON_STATUS = 'https://kohcamp.qq.com/game/seasonpage'
HERO_LIST = 'https://pvp.qq.com/web201605/js/herolist.json'
ALL_ROLE_LIST_V3 = 'https://ssl.kohsocialapp.qq.com:10001/game/allrolelistv3'
USER_PROFILE = 'https://kohcamp.qq.com/userprofile/profile'
PROFILE_INDEX = 'https://kohcamp.qq.com/game/profile/index'
PROFILE_HERO_LIST = 'https://kohcamp.qq.com/game/profile/herolist'
